### ISSUE TITLE
Can not parquet file after "/"

### ISSUE THREAD

**Issue by MrKedrok** [kaaveland/pyarrowfs-adlgen2#2]
hi team, i can not read parquet file after /

i have got error : 

i tried read : 
![image](https://user-images.githubusercontent.com/26300945/100546984-a61d7980-3264-11eb-9b83-fe80f56a66c4.png)

via that command : df = pd.read_parquet('/refined/masterdata/Dimension/dim_type/full/current/', filesystem=fs)

and I got : 
raise ValueError(f'{path} is an illegal path (may not end with /)')
ValueError: masterdata/Dimension/dim_type/full/current/ is an illegal path (may not end with /)

when I read parquet data with full path 
df = pd.read_parquet('/refined/masterdata/Dimension/dim_type/full/current/part-00000-5dd90513-e8ea-4a71-a05b-79e7357bd1a6-c000.snappy.parquet', filesystem=fs)

i did not got error
![image](https://user-images.githubusercontent.com/26300945/100547021-e0871680-3264-11eb-95e2-4b57bc6f7065.png)

Can it be fix ?

**Comment by kaaveland** [comment]
Hi!

Can you attempt to do it like this?

```python
df = pd.read_parquet('/refined/masterdata/Dimension/dim_type/full/current', filesystem=fs)
```

The filesystem implementation will refuse to work with trailing slash on directory names, but it should work fine without the trailing slash.

**Comment by MrKedrok** [comment]
Hi! 
still, I have a problem 

pyarrow.lib.ArrowInvalid: GetFileInfo() yielded path 'refined/masterdata/Dimension/dim_type/full/current/part-00000-5dd90513-e8ea-4a71-a05b-79e7357bd1a6-c000.snappy.parquet', which is outside base dir '/refined/mas
terdata/Dimension/dim_type/full/current'


![image](https://user-images.githubusercontent.com/26300945/100620121-58654780-331e-11eb-9b3b-35b25b770eb0.png)


only the full path is working.

**Comment by kaaveland** [comment]
Oh no, I see what's going on. You're sending the path with a leading slash `/`, but pyarrowfs-adlgen2 has no concept of a "root" as such. So it's returning paths without the leading slash.

I will try to check how much hassle it is to support both leading and trailing slashes. Either way, need to do some work here since this is clearly difficult to use right.

Meanwhile, it would be cool if you could test without the leading path as well, ie: `refined/masterdata/Dimension/dim_type/full/current`.

**Comment by kaaveland** [comment]
I've released 0.1.2 now, which should deal with both trailing and leading slashes.

**Comment by MrKedrok** [comment]
Hi ! thanks a lot but i have error when i trying import it on my AKS pod
![image](https://user-images.githubusercontent.com/26300945/101623493-d27d8680-3a18-11eb-9d7e-6d79ca36bf48.png)

Error: >>> import pyarrowfs_adlgen2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pyarrowfs_adlgen2/__init__.py", line 1, in <module>
    from .core import FilesystemHandler, AccountHandler
  File "/usr/local/lib/python3.7/dist-packages/pyarrowfs_adlgen2/core.py", line 22, in <module>
    import azure.storage.filedatalake
  File "/usr/local/lib/python3.7/dist-packages/azure/storage/filedatalake/__init__.py", line 7, in <module>
    from ._download import StorageStreamDownloader
  File "/usr/local/lib/python3.7/dist-packages/azure/storage/filedatalake/_download.py", line 6, in <module>
    from ._deserialize import from_blob_properties
  File "/usr/local/lib/python3.7/dist-packages/azure/storage/filedatalake/_deserialize.py", line 15, in <module>
    from ._models import FileProperties, DirectoryProperties, LeaseProperties
  File "/usr/local/lib/python3.7/dist-packages/azure/storage/filedatalake/_models.py", line 10, in <module>
    from azure.storage.blob import LeaseProperties as BlobLeaseProperties
  File "/usr/local/lib/python3.7/dist-packages/azure/storage/blob/__init__.py", line 10, in <module>
    from ._blob_client import BlobClient
  File "/usr/local/lib/python3.7/dist-packages/azure/storage/blob/_blob_client.py", line 24, in <module>
    from ._shared.base_client import StorageAccountHostsMixin, parse_connection_str, parse_query
  File "/usr/local/lib/python3.7/dist-packages/azure/storage/blob/_shared/base_client.py", line 42, in <module>
    from .constants import STORAGE_OAUTH_SCOPE, SERVICE_HOST_BASE, CONNECTION_TIMEOUT, READ_TIMEOUT
  File "/usr/local/lib/python3.7/dist-packages/azure/storage/blob/_shared/constants.py", line 8, in <module>
    from .._generated.version import VERSION
  File "/usr/local/lib/python3.7/dist-packages/azure/storage/blob/_generated/__init__.py", line 12, in <module>
    from ._azure_blob_storage import AzureBlobStorage
  File "/usr/local/lib/python3.7/dist-packages/azure/storage/blob/_generated/_azure_blob_storage.py", line 13, in <module>
    from msrest import Serializer, Deserializer
  File "/usr/local/lib/python3.7/dist-packages/msrest/__init__.py", line 29, in <module>
    from .service_client import ServiceClient, SDKClient
  File "/usr/local/lib/python3.7/dist-packages/msrest/service_client.py", line 38, in <module>
    from .authentication import Authentication
  File "/usr/local/lib/python3.7/dist-packages/msrest/authentication.py", line 30, in <module>
    import requests_oauthlib as oauth
  File "/usr/local/lib/python3.7/dist-packages/requests_oauthlib/__init__.py", line 12, in <module>
    if requests.__version__ < "2.0.0":
TypeError: '<' not supported between instances of 'module' and 'str'

**Comment by MrKedrok** [comment]
Hi thanks a lot !

right now i can read data without file name ! :)
